puts "The students of Villains Academy"
puts "__________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kreuger"
puts "The Joker"
puts "Jeoffrey Baratheon"
puts "Norman Bates"
print "Overall, we have"
print "11"
puts "great students"

#print doesnt add new line characters while puts does
#if we wanted to break them up we could do this = print "line14\nline15\nline16"
#this has to be in "" not ''
