puts "The students of Villains Academy"
puts "__________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kreuger"
puts "The Joker"
puts "Jeoffrey Baratheon"
puts "Norman Bates"
